CodingNameKiki

high

# A wrong amount of totalSupply() will break the calculation for all account balances.

## Summary
Duo to the exploit, l described in my other report for the `withdraw()` and `withdrawAll()` functions:
`"Some funds can be locked in the vault without a way for retrieving them."`
The same problem leads to another high risk issue, which will occur and l believe it should be described separately.
Both of the issues origin from the same mistake, but they lead to different exploits and different ways to lose funds.

//Note this issue results in a different outcome, than the wrong amount of `totalShares()` report.
//With the exploit explained in "Vulnerability Detail", here users will actually receive more funds, than the expected amount in 
//the first place, since the amount of `totalSupply()` is way higher and wrong, duo to someone else's stucked funds in the vault.


## Vulnerability Detail
Like l described in my previous report:
The function `withdraw()` is used from the users to redeem a certain amount shares of myLINK for LINK, and the function `withdrawAll()` allow users to completely withdraw from the vault by redeeming all of their shares of myLINK for LINK.

The functions burn the amount of shares wanted to be withdrawn by the user. 

https://github.com/sherlock-audit/2022-10-mycelium/blob/main/mylink-contracts/src/Vault.sol#L159

After that it transfers the LINK tokens from the vault to the user.
However the function uses `transfer()` that does not check the return value, if for some reason the IERC20 transfer is temporarily failing. As the return value of the external call is not checked and returns only boolean value indicating success, if it has failed, the contract wouldn’t know about it, and the function will finish “successfully”.

https://github.com/sherlock-audit/2022-10-mycelium/blob/main/mylink-contracts/src/Vault.sol#L161

Result: 
User's shares were burned, even tho he didn't receive any tokens from the vault. This way his LINK tokens are stucked in the vault, which leads to another undesired behaviour, since the amount of shares were burned, but the LINK tokens are still staying in the vault, the `totalSupply()` will be way higher and wrong, than the expected amount in the first place. 

This way by having a way higher `totalSupply()` of the LINK tokens in the vault and by applying the formula, which calculates the accounts balances:

https://github.com/sherlock-audit/2022-10-mycelium/blob/main/mylink-contracts/src/Vault.sol#L18

The users will actually get more tokens, duo to someone else's stucked LINK tokens in the vault.

## Impact
With the describe issue above users will receive more tokens, duo to the stucked LINK tokens in the vault, resulting into way higher amount of the `totalSupply()`.

## Code Snippet

https://github.com/sherlock-audit/2022-10-mycelium/blob/main/mylink-contracts/src/Vault.sol#L153-L164

https://github.com/sherlock-audit/2022-10-mycelium/blob/main/mylink-contracts/src/Vault.sol#L174-L185

https://github.com/sherlock-audit/2022-10-mycelium/blob/main/mylink-contracts/src/Vault.sol#L15-L19

## Tool used

Manual Review

## Recommendation
Add a check to ensure that the transfer didn't fail, you can either use require statement or openzeppelin's SafeERC20 wrappers.
By following the recommendition steps the function `withdraw()` and `withdrawAll()` will revert, if the transfer fails.

1.You can use require statement: https://gist.github.com/CodingNameKiki/5969109dcb853ccd24f14f7630c39dae
2.You can use openzeppelin's SafeERC20: https://gist.github.com/CodingNameKiki/b8c6255e3cad1c3eb48023528449f7c4